version: "3.9"

services:

  vaadin_app:
    container_name: vaadin_app
    image: vaadin-java-app:1.0
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - vaadin_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://vaadin_db:3306/Educantrol
      SPRING_DATASOURCE_USERNAME: luis
      SPRING_DATASOURCE_PASSWORD: master
      PORT: 8080

  vaadin_db:
    container_name: vaadin_db
    image: mariadb:10.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Educantrol
      MYSQL_USER: luis
      MYSQL_PASSWORD: master