server.port=${PORT:8080}
logging.level.org.atmosphere=warn

# Configuración de MariaDB (variables de entorno)
spring.datasource.url=${SPRING_DATASOURCE_URL}?useSSL=false
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Configuración de Vaadin
vaadin.launch-browser=false
vaadin.allowed-packages=com.vaadin,org.vaadin,com.example.application
